[book]
authors = ["faja"]
language = "en"
src = "src"
title = "Manuals"

[build]
create-missing = false

[output.html]
default-theme = "ayu"
additional-css = ["custom.css"]

[output.html.fold]
enable = true
level = 0
